# File has been autogenerated by gen_game_data.py
# Generated on: 2024-08-24T04:54:45+00:00
# Don't edit by hand!

# Copyright (C) 2024 Christopher J. Kucera
#
# swh2save is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


class GameData:

    def __init__(self, name, label):
        self.name = name
        self.label = label

    def __str__(self):
        return f'{self.label} ({self.name})'

    def __lt__(self, other):
        if isinstance(other, GameData):
            return self.label.casefold() < other.label.casefold()
        else:
            return self.label.casefold() < other.casefold()

    def __gt__(self, other):
        if isinstance(other, GameData):
            return self.label.casefold() > other.label.casefold()
        else:
            return self.label.casefold() > other.casefold()

class Crew(GameData):
    pass


class KeyItem(GameData):
    pass


class Upgrade(GameData):

    def __init__(self, name, label, keyitem, category):
        super().__init__(name, label)
        self.keyitem = keyitem
        self.category = category


class Hat(GameData):
    pass


class ShipEquipment(GameData):
    pass


class Utility(GameData):
    pass


class Weapon(GameData):
    pass


CREW = {
        'daisy': Crew(
            'daisy',
            "Daisy",
            ),
        'wesley': Crew(
            'wesley',
            "Wesley",
            ),
        'judy': Crew(
            'judy',
            "Judy",
            ),
        'crow': Crew(
            'crow',
            "Crowbar",
            ),
        'diver': Crew(
            'diver',
            "Sola",
            ),
        'poe': Crew(
            'poe',
            "Poe",
            ),
        'cornelius': Crew(
            'cornelius',
            "Cornelius",
            ),
        'adventure_boy': Crew(
            'adventure_boy',
            "Tristan",
            ),
        'chimney': Crew(
            'chimney',
            "Chimney",
            ),
        'cyclop': Crew(
            'cyclop',
            "Beacon",
            ),
        }

KEY_ITEMS = {
        'steel_plates_west_caribbea_c': KeyItem(
            'steel_plates_west_caribbea_c',
            "Pressure Tank",
            ),
        'ship_booster': KeyItem(
            'ship_booster',
            "Propeller Booster",
            ),
        'keyitem_ship_shield': KeyItem(
            'keyitem_ship_shield',
            "Energy Shield",
            ),
        'atomic_engine': KeyItem(
            'atomic_engine',
            "Atomic Engine",
            ),
        'keyitem_ship_ram': KeyItem(
            'keyitem_ship_ram',
            "Ram",
            ),
        'keyitem_glow_rod_01': KeyItem(
            'keyitem_glow_rod_01',
            "Glow Rod",
            ),
        'keyitem_glow_rod_02': KeyItem(
            'keyitem_glow_rod_02',
            "Glow Rod",
            ),
        'keyitem_glow_rod_03': KeyItem(
            'keyitem_glow_rod_03',
            "Glow Rod",
            ),
        'keyitem_glow_rod_04': KeyItem(
            'keyitem_glow_rod_04',
            "Glow Rod",
            ),
        'keyitem_glow_rod_05': KeyItem(
            'keyitem_glow_rod_05',
            "Glow Rod",
            ),
        'keyitem_glow_rod_06': KeyItem(
            'keyitem_glow_rod_06',
            "Glow Rod",
            ),
        'keyitem_krakenhorn': KeyItem(
            'keyitem_krakenhorn',
            "The Kraken Horn",
            ),
        'keyitem_geiger_counter': KeyItem(
            'keyitem_geiger_counter',
            "Geiger Counter",
            ),
        'hub_c_heist_blueprints': KeyItem(
            'hub_c_heist_blueprints',
            "Navy Fort Blueprints",
            ),
        'west_caribbea_mechanic_heist_key': KeyItem(
            'west_caribbea_mechanic_heist_key',
            "Stockades Key",
            ),
        'arctica_hub_d_heist_key': KeyItem(
            'arctica_hub_d_heist_key',
            "Research Facility Key",
            ),
        'east_caribbea_navy_boss_key': KeyItem(
            'east_caribbea_navy_boss_key',
            "Piston's Palace Key",
            ),
        'vec_tech_communicators': KeyItem(
            'vec_tech_communicators',
            "Vec-Tech Communicators",
            ),
        'hub_c_flagship_codes': KeyItem(
            'hub_c_flagship_codes',
            "Secret Navy Codes",
            ),
        'keyitem_parley_invitation': KeyItem(
            'keyitem_parley_invitation',
            "Parley Invitation",
            ),
        'keyitem_celestial_gear_01': KeyItem(
            'keyitem_celestial_gear_01',
            "Golden Gear",
            ),
        'keyitem_celestial_gear_02': KeyItem(
            'keyitem_celestial_gear_02',
            "Amethyst Gear",
            ),
        'keyitem_celestial_gear_03': KeyItem(
            'keyitem_celestial_gear_03',
            "Emerald Gear",
            ),
        'keyitem_celestial_gear_04': KeyItem(
            'keyitem_celestial_gear_04',
            "Sapphire Gear",
            ),
        'keyitem_celestial_gear_05': KeyItem(
            'keyitem_celestial_gear_05',
            "Diamond Gear",
            ),
        'keyitem_celestial_gear_06': KeyItem(
            'keyitem_celestial_gear_06',
            "Citrine Gear",
            ),
        'keyitem_celestial_gear_07': KeyItem(
            'keyitem_celestial_gear_07',
            "Ruby Gear",
            ),
        }

UPGRADES = {
        'ship_boost_00': Upgrade(
            'ship_boost_00',
            "Propeller Booster",
            'ship_booster',
            'ability',
            ),
        'dive_00': Upgrade(
            'dive_00',
            "Pressure Tank",
            'steel_plates_west_caribbea_c',
            'ability',
            ),
        'dive_02': Upgrade(
            'dive_02',
            "Atomic Engine",
            'atomic_engine',
            'ability',
            ),
        'geiger_counter_00': Upgrade(
            'geiger_counter_00',
            "Geiger Counter",
            'keyitem_geiger_counter',
            'ability',
            ),
        'geiger_counter_01': Upgrade(
            'geiger_counter_01',
            "Atomic Engine",
            'atomic_engine',
            'ability',
            ),
        'equip_00': Upgrade(
            'equip_00',
            "Sub Equipment Terminal",
            None,
            'main',
            ),
        'gym_00': Upgrade(
            'gym_00',
            "Personal Upgrade Terminal",
            None,
            'main',
            ),
        'gym_01': Upgrade(
            'gym_01',
            "Improved Personal Upgrades",
            None,
            'main',
            ),
        'guildhall_00': Upgrade(
            'guildhall_00',
            "Job Upgrade Terminal",
            None,
            'main',
            ),
        'guildhall_01': Upgrade(
            'guildhall_01',
            "Improved Job Upgrades",
            None,
            'main',
            ),
        'guildhall_02': Upgrade(
            'guildhall_02',
            "Epic Job Upgrades",
            None,
            'main',
            ),
        'equip_slot_00': Upgrade(
            'equip_slot_00',
            "Sub Equipment Slot",
            None,
            'main',
            ),
        'equip_slot_01': Upgrade(
            'equip_slot_01',
            "Sub Equipment Slot",
            None,
            'main',
            ),
        'equip_slot_02': Upgrade(
            'equip_slot_02',
            "Sub Equipment Slot",
            None,
            'main',
            ),
        'equip_slot_03': Upgrade(
            'equip_slot_03',
            "Sub Equipment Slot",
            None,
            'main',
            ),
        'equip_slot_04': Upgrade(
            'equip_slot_04',
            "Sub Equipment Slot",
            None,
            'main',
            ),
        'equip_slot_05': Upgrade(
            'equip_slot_05',
            "Sub Equipment Slot",
            None,
            'main',
            ),
        'sonar': Upgrade(
            'sonar',
            "Echo Locator",
            None,
            'main',
            ),
        'bunk_bed_00': Upgrade(
            'bunk_bed_00',
            "Bunk Bed",
            None,
            'main',
            ),
        'bunk_bed_01': Upgrade(
            'bunk_bed_01',
            "Bunk Bed",
            None,
            'main',
            ),
        'extra_cog_00': Upgrade(
            'extra_cog_00',
            "Extra Cog",
            None,
            'main',
            ),
        'extra_cog_01': Upgrade(
            'extra_cog_01',
            "Extra Cog",
            None,
            'main',
            ),
        'extra_cog_02': Upgrade(
            'extra_cog_02',
            "Extra Cog",
            None,
            'main',
            ),
        'extra_cog_03': Upgrade(
            'extra_cog_03',
            "Extra Cog",
            None,
            'main',
            ),
        'extra_utility_00': Upgrade(
            'extra_utility_00',
            "Utility Belts",
            None,
            'main',
            ),
        'exp_bonus_00': Upgrade(
            'exp_bonus_00',
            "Combat Guidebook",
            None,
            'main',
            ),
        'exp_bonus_01': Upgrade(
            'exp_bonus_01',
            "Advanced Combat Guidebook",
            None,
            'main',
            ),
        'money_bonus_00': Upgrade(
            'money_bonus_00',
            "Water Purifier",
            None,
            'main',
            ),
        'money_bonus_01': Upgrade(
            'money_bonus_01',
            "Purifier Efficiency",
            None,
            'main',
            ),
        'crew_health_00': Upgrade(
            'crew_health_00',
            "Dumbbells",
            None,
            'main',
            ),
        'crew_health_01': Upgrade(
            'crew_health_01',
            "Heavy Dumbbells",
            None,
            'main',
            ),
        'crew_health_02': Upgrade(
            'crew_health_02',
            "Massive Dumbbells",
            None,
            'main',
            ),
        'crew_melee_00': Upgrade(
            'crew_melee_00',
            "Punching Bag",
            None,
            'main',
            ),
        'crew_move_00': Upgrade(
            'crew_move_00',
            "Treadmill",
            None,
            'main',
            ),
        'jobupgrade_tank_1': Upgrade(
            'jobupgrade_tank_1',
            "Trusty Sidearm+",
            None,
            'guildhall',
            ),
        'jobupgrade_tank_2': Upgrade(
            'jobupgrade_tank_2',
            "Payback+",
            None,
            'guildhall',
            ),
        'jobupgrade_tank_3': Upgrade(
            'jobupgrade_tank_3',
            "Hard Shell+",
            None,
            'guildhall',
            ),
        'jobupgrade_boomer_1': Upgrade(
            'jobupgrade_boomer_1',
            "Hidden Explosives+",
            None,
            'guildhall',
            ),
        'jobupgrade_boomer_2': Upgrade(
            'jobupgrade_boomer_2',
            "Slot Machine+",
            None,
            'guildhall',
            ),
        'jobupgrade_boomer_3': Upgrade(
            'jobupgrade_boomer_3',
            "Loose Cannon+",
            None,
            'guildhall',
            ),
        'jobupgrade_engineer_1': Upgrade(
            'jobupgrade_engineer_1',
            "Greased Up+",
            None,
            'guildhall',
            ),
        'jobupgrade_engineer_2': Upgrade(
            'jobupgrade_engineer_2',
            "Amped Up+",
            None,
            'guildhall',
            ),
        'jobupgrade_engineer_3': Upgrade(
            'jobupgrade_engineer_3',
            "Break+",
            None,
            'guildhall',
            ),
        'jobupgrade_sniper_1': Upgrade(
            'jobupgrade_sniper_1',
            "Power Shot+",
            None,
            'guildhall',
            ),
        'jobupgrade_sniper_2': Upgrade(
            'jobupgrade_sniper_2',
            "Focus+",
            None,
            'guildhall',
            ),
        'jobupgrade_sniper_3': Upgrade(
            'jobupgrade_sniper_3',
            "Hunter's Mark+",
            None,
            'guildhall',
            ),
        'jobupgrade_reaper_1': Upgrade(
            'jobupgrade_reaper_1',
            "Warcry+",
            None,
            'guildhall',
            ),
        'jobupgrade_reaper_2': Upgrade(
            'jobupgrade_reaper_2',
            "Rage+",
            None,
            'guildhall',
            ),
        'jobupgrade_reaper_3': Upgrade(
            'jobupgrade_reaper_3',
            "Harvest+",
            None,
            'guildhall',
            ),
        'jobupgrade_flanker_1': Upgrade(
            'jobupgrade_flanker_1',
            "Backbiter+",
            None,
            'guildhall',
            ),
        'jobupgrade_flanker_2': Upgrade(
            'jobupgrade_flanker_2',
            "Sidestep+",
            None,
            'guildhall',
            ),
        'jobupgrade_flanker_3': Upgrade(
            'jobupgrade_flanker_3',
            "Wheel 'n Deal+",
            None,
            'guildhall',
            ),
        'celestial_gear_01': Upgrade(
            'celestial_gear_01',
            "Golden Gear",
            'keyitem_celestial_gear_01',
            'ability',
            ),
        'celestial_gear_02': Upgrade(
            'celestial_gear_02',
            "Amethyst Gear",
            'keyitem_celestial_gear_02',
            'ability',
            ),
        'celestial_gear_03': Upgrade(
            'celestial_gear_03',
            "Emerald Gear",
            'keyitem_celestial_gear_03',
            'ability',
            ),
        'celestial_gear_04': Upgrade(
            'celestial_gear_04',
            "Sapphire Gear",
            'keyitem_celestial_gear_04',
            'ability',
            ),
        'celestial_gear_05': Upgrade(
            'celestial_gear_05',
            "Diamond Gear",
            'keyitem_celestial_gear_05',
            'ability',
            ),
        'celestial_gear_06': Upgrade(
            'celestial_gear_06',
            "Citrine Gear",
            'keyitem_celestial_gear_06',
            'ability',
            ),
        'celestial_gear_07': Upgrade(
            'celestial_gear_07',
            "Ruby Gear",
            'keyitem_celestial_gear_07',
            'ability',
            ),
        }

HATS = {
        'hat_captain': Hat(
            'hat_captain',
            "Captain's Hat",
            ),
        'hat_daisy': Hat(
            'hat_daisy',
            "Flop Cap",
            ),
        'hat_wesley': Hat(
            'hat_wesley',
            "Pickelhaube",
            ),
        'hat_cornelius': Hat(
            'hat_cornelius',
            "Fez",
            ),
        'hat_poe': Hat(
            'hat_poe',
            "Roguish Antenna",
            ),
        'hat_judy': Hat(
            'hat_judy',
            "Leather Hat",
            ),
        'hat_adventure_boy': Hat(
            'hat_adventure_boy',
            "Spiky Hair",
            ),
        'hat_diver': Hat(
            'hat_diver',
            "A Simple Valve",
            ),
        'hat_crow': Hat(
            'hat_crow',
            "Soft Cloth Hat",
            ),
        'hat_cyclop': Hat(
            'hat_cyclop',
            "A Simple Beanie",
            ),
        'hat_chimney': Hat(
            'hat_chimney',
            "Sailor's Cap",
            ),
        'hat_mother': Hat(
            'hat_mother',
            "Krakenbane's Hat",
            ),
        'hat_piper': Hat(
            'hat_piper',
            "Captain Faraday's Hat",
            ),
        'hat_revolution_beret': Hat(
            'hat_revolution_beret',
            "Rebellious Beret",
            ),
        'hat_navy_seabot': Hat(
            'hat_navy_seabot',
            "Navy Soldier Cap",
            ),
        'hat_navy_seabot_elite': Hat(
            'hat_navy_seabot_elite',
            "Elite Soldier Cap",
            ),
        'hat_navy_seabot_machinegunner': Hat(
            'hat_navy_seabot_machinegunner',
            "Machinegunner Hat",
            ),
        'hat_navy_seabot_machinegunner_elite': Hat(
            'hat_navy_seabot_machinegunner_elite',
            "Elite Machinegunner Hat",
            ),
        'hat_navy_seabot_shotgunner': Hat(
            'hat_navy_seabot_shotgunner',
            "Shotgunner Hat",
            ),
        'hat_navy_seabot_shotgunner_elite': Hat(
            'hat_navy_seabot_shotgunner_elite',
            "Elite Shotgunner Hat",
            ),
        'hat_navy_seabot_sniper': Hat(
            'hat_navy_seabot_sniper',
            "Sniper Goggle",
            ),
        'hat_navy_seabot_sniper_elite': Hat(
            'hat_navy_seabot_sniper_elite',
            "Elite Sniper Goggle",
            ),
        'hat_navy_seabot_swordsman': Hat(
            'hat_navy_seabot_swordsman',
            "Swordsman's Hat",
            ),
        'hat_navy_seabot_swordsman_elite': Hat(
            'hat_navy_seabot_swordsman_elite',
            "Elite Swordsman's Hat",
            ),
        'hat_navy_seabot_rare01': Hat(
            'hat_navy_seabot_rare01',
            "Army Helmet",
            ),
        'hat_navy_seabot_rare02': Hat(
            'hat_navy_seabot_rare02',
            "Safari Hat",
            ),
        'hat_navy_seabot_rare03': Hat(
            'hat_navy_seabot_rare03',
            "Cowboy Hat",
            ),
        'hat_navy_seabot_rare04': Hat(
            'hat_navy_seabot_rare04',
            "Bearskin",
            ),
        'hat_navy_seabot_fire': Hat(
            'hat_navy_seabot_fire',
            "Fire helmet",
            ),
        'hat_navy_seabot_bigsteve': Hat(
            'hat_navy_seabot_bigsteve',
            "Floppy Hat",
            ),
        'hat_navy_seabot_tough': Hat(
            'hat_navy_seabot_tough',
            "Iron Mask",
            ),
        'hat_navy_seabot_roaster': Hat(
            'hat_navy_seabot_roaster',
            "Savory Bucket",
            ),
        'hat_navy_guard': Hat(
            'hat_navy_guard',
            "Navy Guard Hat",
            ),
        'hat_navy_guard_elite': Hat(
            'hat_navy_guard_elite',
            "Elite Guard Hat",
            ),
        'hat_navy_guard_roaster': Hat(
            'hat_navy_guard_roaster',
            "Lit Candle",
            ),
        'hat_navy_commander': Hat(
            'hat_navy_commander',
            "Commander Hat",
            ),
        'hat_navy_commander_elite': Hat(
            'hat_navy_commander_elite',
            "Elite Commander Hat",
            ),
        'hat_navy_commander_rare01': Hat(
            'hat_navy_commander_rare01',
            "Pilot Hat",
            ),
        'hat_navy_commander_rare02': Hat(
            'hat_navy_commander_rare02',
            "The Bonaparte",
            ),
        'hat_navy_commander_dean': Hat(
            'hat_navy_commander_dean',
            "Rugged Veteran's Hat",
            ),
        'hat_navy_commander_warden': Hat(
            'hat_navy_commander_warden',
            "Prison Warden Hat",
            ),
        'hat_navy_commander_fancy01': Hat(
            'hat_navy_commander_fancy01',
            "Fancier Wig",
            ),
        'hat_navy_commander_fancy02': Hat(
            'hat_navy_commander_fancy02',
            "Fancy Wig",
            ),
        'hat_navy_commander_fancy03': Hat(
            'hat_navy_commander_fancy03',
            "...Fancy Wig?",
            ),
        'hat_navy_commander_roaster': Hat(
            'hat_navy_commander_roaster',
            "Very Cool Cap",
            ),
        'hat_navy_recruit': Hat(
            'hat_navy_recruit',
            "Recruit Hat",
            ),
        'hat_navy_recruit_rare01': Hat(
            'hat_navy_recruit_rare01',
            "Paper Boat",
            ),
        'hat_navy_fabio': Hat(
            'hat_navy_fabio',
            "Glorious Pompadour",
            ),
        'hat_navy_mech_operator': Hat(
            'hat_navy_mech_operator',
            "Complex Navy Hat",
            ),
        'hat_navy_drone': Hat(
            'hat_navy_drone',
            "Blue Rotating Beacon",
            ),
        'hat_navy_drone_rare01': Hat(
            'hat_navy_drone_rare01',
            "Party Light",
            ),
        'hat_navy_bomb': Hat(
            'hat_navy_bomb',
            "Heated Propeller",
            ),
        'hat_pirate_totem_bearer': Hat(
            'hat_pirate_totem_bearer',
            "Occult Cone",
            ),
        'hat_pirate_totem_bearer_bone': Hat(
            'hat_pirate_totem_bearer_bone',
            "Occult Bone Cone",
            ),
        'hat_pirate_totem_bearer_ice': Hat(
            'hat_pirate_totem_bearer_ice',
            "Occult Ice Cone",
            ),
        'hat_pirate_totem_bearer_retribution': Hat(
            'hat_pirate_totem_bearer_retribution',
            "Occult Retribution Cone",
            ),
        'hat_pirate_totem_bearer_lightning': Hat(
            'hat_pirate_totem_bearer_lightning',
            "Occult Conductor Cone",
            ),
        'hat_pirate_totem_bearer_rare01': Hat(
            'hat_pirate_totem_bearer_rare01',
            "Crown of Thorns",
            ),
        'hat_pirate_totem_bearer_pain': Hat(
            'hat_pirate_totem_bearer_pain',
            "Knife in the Head",
            ),
        'hat_pirate_skelebot': Hat(
            'hat_pirate_skelebot',
            "Small Spiky Helmet",
            ),
        'hat_pirate_skelebot_ice': Hat(
            'hat_pirate_skelebot_ice',
            "Cool Cube",
            ),
        'hat_pirate_swab': Hat(
            'hat_pirate_swab',
            "Seashellmet",
            ),
        'hat_pirate_swab_elite': Hat(
            'hat_pirate_swab_elite',
            "Horned Seashell",
            ),
        'hat_pirate_swab_ice': Hat(
            'hat_pirate_swab_ice',
            "Fur-Lined Seashell Hat",
            ),
        'hat_pirate_swab_tough': Hat(
            'hat_pirate_swab_tough',
            "Uni-horn",
            ),
        'hat_pirate_swab_rare01': Hat(
            'hat_pirate_swab_rare01',
            "Tinfoil Hat",
            ),
        'hat_pirate_swab_rare02': Hat(
            'hat_pirate_swab_rare02',
            "Seagull Nest",
            ),
        'hat_pirate_swab_rare03': Hat(
            'hat_pirate_swab_rare03',
            "Viking Helmet",
            ),
        'hat_pirate_berserker': Hat(
            'hat_pirate_berserker',
            "Bull Horns",
            ),
        'hat_pirate_berserker_ice': Hat(
            'hat_pirate_berserker_ice',
            "Icy Horns",
            ),
        'hat_pirate_berserker_rare01': Hat(
            'hat_pirate_berserker_rare01',
            "Cardboard Box",
            ),
        'hat_pirate_berserker_rare02': Hat(
            'hat_pirate_berserker_rare02',
            "Pretty Bow",
            ),
        'hat_pirate_berserker_parley': Hat(
            'hat_pirate_berserker_parley',
            "Propeller Cap",
            ),
        'hat_pirate_morgan': Hat(
            'hat_pirate_morgan',
            "Morgan's Spire",
            ),
        'hat_pirate_bomb': Hat(
            'hat_pirate_bomb',
            "Frosty Propeller",
            ),
        'hat_atomic_reviver': Hat(
            'hat_atomic_reviver',
            "Atomic Helm",
            ),
        'hat_atomic_reviver_king': Hat(
            'hat_atomic_reviver_king',
            "Infinity Crown",
            ),
        'hat_atomic_reviver_rare01': Hat(
            'hat_atomic_reviver_rare01',
            "Graduate Hat",
            ),
        'hat_atomic_reviver_rare02': Hat(
            'hat_atomic_reviver_rare02',
            "Octopus",
            ),
        'hat_atomic_flying_reviver': Hat(
            'hat_atomic_flying_reviver',
            "Crystal Crown",
            ),
        'hat_atomic_flying_reviver_rare01': Hat(
            'hat_atomic_flying_reviver_rare01',
            "Marvin's Helmet",
            ),
        'hat_atomic_walking_bomb': Hat(
            'hat_atomic_walking_bomb',
            "Delectable Cone",
            ),
        'hat_atomic_walking_bomb_rare01': Hat(
            'hat_atomic_walking_bomb_rare01',
            "Jellyfish",
            ),
        'hat_atomic_mimic': Hat(
            'hat_atomic_mimic',
            "Mimic Mask",
            ),
        'hat_atomic_mech_operator': Hat(
            'hat_atomic_mech_operator',
            "Crown of Reckoning",
            ),
        'hat_atomic_water_scientist': Hat(
            'hat_atomic_water_scientist',
            "Band of Icy Revenge",
            ),
        'hat_shop_fish': Hat(
            'hat_shop_fish',
            "A Fish",
            ),
        'hat_shop_fur': Hat(
            'hat_shop_fur',
            "Fur Hat",
            ),
        'hat_shop_ushanka': Hat(
            'hat_shop_ushanka',
            "Ushanka",
            ),
        'hat_shop_rain': Hat(
            'hat_shop_rain',
            "Sylvester",
            ),
        'hat_shop_kanga': Hat(
            'hat_shop_kanga',
            "Stylish Hat",
            ),
        'hat_shop_valkyrie': Hat(
            'hat_shop_valkyrie',
            "Valkyrie Helmet",
            ),
        'hat_shop_santa': Hat(
            'hat_shop_santa',
            "Jolly Hat",
            ),
        'hat_shop_fruit': Hat(
            'hat_shop_fruit',
            "Fruity Hat",
            ),
        'hat_shop_snorkel': Hat(
            'hat_shop_snorkel',
            "Snorkling Gear",
            ),
        'hat_shop_screen': Hat(
            'hat_shop_screen',
            "Green Screen",
            ),
        'hat_shop_straw': Hat(
            'hat_shop_straw',
            "Straw Hat",
            ),
        'hat_shop_wickedshades': Hat(
            'hat_shop_wickedshades',
            "Wicked Shades",
            ),
        'hat_shop_top': Hat(
            'hat_shop_top',
            "Top Hat",
            ),
        'hat_shop_icecream': Hat(
            'hat_shop_icecream',
            "Magical Horn",
            ),
        'hat_shop_bandana': Hat(
            'hat_shop_bandana',
            "Purple bandana",
            ),
        }

SHIP_EQUIPMENT = {
        'ship_equipment_torpedo_01': ShipEquipment(
            'ship_equipment_torpedo_01',
            "Torpedo I",
            ),
        'ship_equipment_torpedo_02': ShipEquipment(
            'ship_equipment_torpedo_02',
            "Torpedo II",
            ),
        'ship_equipment_torpedo_02_rare': ShipEquipment(
            'ship_equipment_torpedo_02_rare',
            "Rapid Torpedo",
            ),
        'ship_equipment_torpedo_03': ShipEquipment(
            'ship_equipment_torpedo_03',
            "Torpedo III",
            ),
        'ship_equipment_machinegun_01': ShipEquipment(
            'ship_equipment_machinegun_01',
            "Machine Guns I",
            ),
        'ship_equipment_machinegun_02': ShipEquipment(
            'ship_equipment_machinegun_02',
            "Machine Guns II",
            ),
        'ship_equipment_machinegun_03': ShipEquipment(
            'ship_equipment_machinegun_03',
            "Machine Guns III",
            ),
        'ship_equipment_micro_torpedo_01': ShipEquipment(
            'ship_equipment_micro_torpedo_01',
            "Micro Torpedo I",
            ),
        'ship_equipment_micro_torpedo_02': ShipEquipment(
            'ship_equipment_micro_torpedo_02',
            "Micro Torpedo II",
            ),
        'ship_equipment_laser_01_rare': ShipEquipment(
            'ship_equipment_laser_01_rare',
            "Experimental Side Lasers",
            ),
        'ship_equipment_laser_02': ShipEquipment(
            'ship_equipment_laser_02',
            "Side Lasers",
            ),
        'ship_equipment_charge_laser_01': ShipEquipment(
            'ship_equipment_charge_laser_01',
            "Charge Laser I",
            ),
        'ship_equipment_charge_laser_02': ShipEquipment(
            'ship_equipment_charge_laser_02',
            "Charge Laser II",
            ),
        'ship_equipment_machinegun_heavy_01': ShipEquipment(
            'ship_equipment_machinegun_heavy_01',
            "Heavy Machine Guns I",
            ),
        'ship_equipment_machinegun_heavy_02': ShipEquipment(
            'ship_equipment_machinegun_heavy_02',
            "Heavy Machine Guns II",
            ),
        'ship_equipment_machinegun_heavy_03': ShipEquipment(
            'ship_equipment_machinegun_heavy_03',
            "Heavy Machine Guns III",
            ),
        'ship_equipment_cannon_01': ShipEquipment(
            'ship_equipment_cannon_01',
            "Top Cannon I",
            ),
        'ship_equipment_cannon_02': ShipEquipment(
            'ship_equipment_cannon_02',
            "Top Cannon II",
            ),
        'ship_equipment_machinegun_top_01': ShipEquipment(
            'ship_equipment_machinegun_top_01',
            "Top Machinegun",
            ),
        'ship_equipment_laser_top_01': ShipEquipment(
            'ship_equipment_laser_top_01',
            "Top Laser",
            ),
        'ship_equipment_torpedo_top_01': ShipEquipment(
            'ship_equipment_torpedo_top_01',
            "Top Torpedo",
            ),
        'ship_equipment_module_machinegun_reload_01': ShipEquipment(
            'ship_equipment_module_machinegun_reload_01',
            "Machine Gun Auto-loader I",
            ),
        'ship_equipment_module_machinegun_reload_02': ShipEquipment(
            'ship_equipment_module_machinegun_reload_02',
            "Machine Gun Auto-loader II",
            ),
        'ship_equipment_module_torpedo_damage_01': ShipEquipment(
            'ship_equipment_module_torpedo_damage_01',
            "Torpedo Damage I",
            ),
        'ship_equipment_module_torpedo_damage_02': ShipEquipment(
            'ship_equipment_module_torpedo_damage_02',
            "Torpedo Damage II",
            ),
        'ship_equipment_module_laser_cooldown_rare_01': ShipEquipment(
            'ship_equipment_module_laser_cooldown_rare_01',
            "Laser Cooling Unit I",
            ),
        'ship_equipment_module_laser_cooldown_rare_02': ShipEquipment(
            'ship_equipment_module_laser_cooldown_rare_02',
            "Laser Cooling Unit II",
            ),
        'ship_equipment_module_health_01': ShipEquipment(
            'ship_equipment_module_health_01',
            "Armored Plating I",
            ),
        'ship_equipment_module_health_02': ShipEquipment(
            'ship_equipment_module_health_02',
            "Armored Plating II",
            ),
        'ship_equipment_module_health_03': ShipEquipment(
            'ship_equipment_module_health_03',
            "Armored Plating III",
            ),
        'ship_equipment_module_speed_01': ShipEquipment(
            'ship_equipment_module_speed_01',
            "Engine Booster I",
            ),
        'ship_equipment_module_speed_02': ShipEquipment(
            'ship_equipment_module_speed_02',
            "Engine Booster II",
            ),
        'ship_equipment_module_speed_02_rare': ShipEquipment(
            'ship_equipment_module_speed_02_rare',
            "Elite Engine Booster",
            ),
        'ship_equipment_module_speed_03': ShipEquipment(
            'ship_equipment_module_speed_03',
            "Engine Booster III",
            ),
        'ship_equipment_module_air_01': ShipEquipment(
            'ship_equipment_module_air_01',
            "Auxiliary Air Tank",
            ),
        }

UTILITIES = {
        'utility_repair_01': Utility(
            'utility_repair_01',
            "Repair Kit I",
            ),
        'utility_repair_01_rare': Utility(
            'utility_repair_01_rare',
            "Big Repair Pack",
            ),
        'utility_repair_02': Utility(
            'utility_repair_02',
            "Repair Kit II",
            ),
        'utility_repair_02_rare': Utility(
            'utility_repair_02_rare',
            "Jazzy Repair Record",
            ),
        'utility_repair_03': Utility(
            'utility_repair_03',
            "Repair Kit III",
            ),
        'utility_repair_03_rare': Utility(
            'utility_repair_03_rare',
            "Regeneration Field",
            ),
        'utility_stimpack_rare': Utility(
            'utility_stimpack_rare',
            "Air Stim",
            ),
        'utility_armor_01': Utility(
            'utility_armor_01',
            "Reinforced Plating I",
            ),
        'utility_armor_01_rare': Utility(
            'utility_armor_01_rare',
            "Heavy Reinforced Plating",
            ),
        'utility_armor_01_warm': Utility(
            'utility_armor_01_warm',
            "Heated Plating",
            ),
        'utility_armor_02': Utility(
            'utility_armor_02',
            "Reinforced Plating II",
            ),
        'utility_armor_03': Utility(
            'utility_armor_03',
            "Reinforced Plating III",
            ),
        'utility_grenade_00': Utility(
            'utility_grenade_00',
            "Homemade Grenade",
            ),
        'utility_grenade_01': Utility(
            'utility_grenade_01',
            "Grenade I",
            ),
        'utility_grenade_01_rare': Utility(
            'utility_grenade_01_rare',
            "Quick Grenade",
            ),
        'utility_grenade_02': Utility(
            'utility_grenade_02',
            "Grenade II",
            ),
        'utility_grenade_02_rare': Utility(
            'utility_grenade_02_rare',
            "Mutually Assured Destruction",
            ),
        'utility_grenade_03_ice': Utility(
            'utility_grenade_03_ice',
            "Grenade III",
            ),
        'utility_grenade_03_rare': Utility(
            'utility_grenade_03_rare',
            "Stun Grenade",
            ),
        'utility_grenade_04': Utility(
            'utility_grenade_04',
            "Grenade IV",
            ),
        'utility_grenade_04_rare': Utility(
            'utility_grenade_04_rare',
            "Box of Grenades",
            ),
        'utility_grenade_05': Utility(
            'utility_grenade_05',
            "Grenade V",
            ),
        'utility_grenade_06_rare': Utility(
            'utility_grenade_06_rare',
            "InstaBlast Grenade",
            ),
        'utility_rocket_01_rare': Utility(
            'utility_rocket_01_rare',
            "Portable Rocket",
            ),
        'utility_rocket_02_rare': Utility(
            'utility_rocket_02_rare',
            "Portable Nuke",
            ),
        'utility_sidearm_01': Utility(
            'utility_sidearm_01',
            "Sidearm I",
            ),
        'utility_sidearm_01_rare': Utility(
            'utility_sidearm_01_rare',
            "Sniper Sidearm",
            ),
        'utility_sidearm_02': Utility(
            'utility_sidearm_02',
            "Sidearm II",
            ),
        'utility_sidearm_03': Utility(
            'utility_sidearm_03',
            "Sidearm III",
            ),
        'utility_sidearm_03_rare': Utility(
            'utility_sidearm_03_rare',
            "Quick Sidearm",
            ),
        'utility_sidearm_04': Utility(
            'utility_sidearm_04',
            "Sidearm IV",
            ),
        'utility_sidearm_05': Utility(
            'utility_sidearm_05',
            "Sidearm V",
            ),
        'utility_sidearm_05_rare': Utility(
            'utility_sidearm_05_rare',
            "Box of Sidearms",
            ),
        'utility_sidearm_06_rare': Utility(
            'utility_sidearm_06_rare',
            "Sushi Sidearm",
            ),
        'utility_weapon_charger': Utility(
            'utility_weapon_charger',
            "Weapon Charger",
            ),
        'utility_knuckle_01': Utility(
            'utility_knuckle_01',
            "Knuckles I",
            ),
        'utility_knuckle_01_rare': Utility(
            'utility_knuckle_01_rare',
            "Warm Gloves",
            ),
        'utility_knuckle_02': Utility(
            'utility_knuckle_02',
            "Knuckles II",
            ),
        'utility_warm': Utility(
            'utility_warm',
            "Warm Scarf",
            ),
        'utility_boots_01': Utility(
            'utility_boots_01',
            "Boots",
            ),
        'utility_boots_01_rare': Utility(
            'utility_boots_01_rare',
            "Speed Boots",
            ),
        'utility_boots_crippleproof': Utility(
            'utility_boots_crippleproof',
            "Military Boots",
            ),
        'utility_boots_warm': Utility(
            'utility_boots_warm',
            "Warm Boots",
            ),
        'utility_boots_fireproof': Utility(
            'utility_boots_fireproof',
            "Fireproof Boots",
            ),
        'utility_boots_02': Utility(
            'utility_boots_02',
            "Better Boots",
            ),
        'utility_boots_03_rare': Utility(
            'utility_boots_03_rare',
            "Sonic Boots",
            ),
        'utility_crit_plus_1': Utility(
            'utility_crit_plus_1',
            "Critical Rounds",
            ),
        'utility_scope_01': Utility(
            'utility_scope_01',
            "Scope",
            ),
        'utility_scope_02_rare': Utility(
            'utility_scope_02_rare',
            "Precision Scope",
            ),
        'utility_scope_03': Utility(
            'utility_scope_03',
            "High-powered Scope",
            ),
        'utility_cogs_01': Utility(
            'utility_cogs_01',
            "Cog Chain I",
            ),
        'utility_cogs_02': Utility(
            'utility_cogs_02',
            "Cog Chain II",
            ),
        'utility_cogs_03': Utility(
            'utility_cogs_03',
            "Cog Chain III",
            ),
        'utility_aura_plus': Utility(
            'utility_aura_plus',
            "Aura Booster",
            ),
        'utility_aura_plus_rare': Utility(
            'utility_aura_plus_rare',
            "Super Aura Booster",
            ),
        'utility_radiance_rare': Utility(
            'utility_radiance_rare',
            "Radiance",
            ),
        'utility_taser_rare': Utility(
            'utility_taser_rare',
            "Remote Taser",
            ),
        'utility_armor_boost_01_rare': Utility(
            'utility_armor_boost_01_rare',
            "Sentinel Generator",
            ),
        'utility_jetpack': Utility(
            'utility_jetpack',
            "Jetpack",
            ),
        'utility_goggles_rare': Utility(
            'utility_goggles_rare',
            "Critical Goggles",
            ),
        'utility_goggles_02_rare': Utility(
            'utility_goggles_02_rare',
            "Precision Goggles",
            ),
        'utility_pain_rare': Utility(
            'utility_pain_rare',
            "Pain Amulet",
            ),
        'utility_alloy_rare': Utility(
            'utility_alloy_rare',
            "Titanium Alloy",
            ),
        'utility_damage_rare': Utility(
            'utility_damage_rare',
            "T-1000 Titanium Casings",
            ),
        'utility_cool_rare': Utility(
            'utility_cool_rare',
            "Cooler Unit",
            ),
        'utility_experience_badge_01_rare': Utility(
            'utility_experience_badge_01_rare',
            "Experience Badge",
            ),
        'utility_experience_badge_02_rare': Utility(
            'utility_experience_badge_02_rare',
            "Ultimate Badge",
            ),
        }

WEAPONS = {
        'sniper_00': Weapon(
            'sniper_00',
            "Junk Sniper",
            ),
        'sniper_01': Weapon(
            'sniper_01',
            "Sniper Mk I",
            ),
        'sniper_01_rare': Weapon(
            'sniper_01_rare',
            "Skelectric",
            ),
        'sniper_02': Weapon(
            'sniper_02',
            "Sniper Mk II",
            ),
        'sniper_02_rare': Weapon(
            'sniper_02_rare',
            "Blue Steel",
            ),
        'sniper_03': Weapon(
            'sniper_03',
            "Sniper Mk III",
            ),
        'sniper_03_rare': Weapon(
            'sniper_03_rare',
            "Deliverance",
            ),
        'sniper_04': Weapon(
            'sniper_04',
            "Sniper Mk IV",
            ),
        'sniper_04_rare': Weapon(
            'sniper_04_rare',
            "Deadshot",
            ),
        'sniper_05': Weapon(
            'sniper_05',
            "Sniper Mk V",
            ),
        'sniper_05_rare': Weapon(
            'sniper_05_rare',
            "Matchstick",
            ),
        'sniper_06': Weapon(
            'sniper_06',
            "Atomic Sniper Rifle",
            ),
        'smg_00': Weapon(
            'smg_00',
            "Old SMG",
            ),
        'smg_01': Weapon(
            'smg_01',
            "SMG Mk I",
            ),
        'crossbow_01_rare': Weapon(
            'crossbow_01_rare',
            "Crossbow",
            ),
        'smg_02': Weapon(
            'smg_02',
            "SMG Mk II",
            ),
        'smg_02_rare': Weapon(
            'smg_02_rare',
            "The Visitor",
            ),
        'smg_03': Weapon(
            'smg_03',
            "SMG Mk III",
            ),
        'crossbow_03_rare': Weapon(
            'crossbow_03_rare',
            "The Stapler",
            ),
        'smg_04': Weapon(
            'smg_04',
            "SMG Mk IV",
            ),
        'smg_04_rare': Weapon(
            'smg_04_rare',
            "Chrono Blaster",
            ),
        'smg_05': Weapon(
            'smg_05',
            "SMG Mk V",
            ),
        'crossbow_05_rare': Weapon(
            'crossbow_05_rare',
            "Siphoning Crossbow",
            ),
        'smg_06': Weapon(
            'smg_06',
            "Atomic SMG",
            ),
        'handgun_00': Weapon(
            'handgun_00',
            "Antique Carrion Pistol",
            ),
        'handgun_01': Weapon(
            'handgun_01',
            "Handgun Mk I",
            ),
        'handgun_01_rare': Weapon(
            'handgun_01_rare',
            "Aggie's Special",
            ),
        'handgun_02': Weapon(
            'handgun_02',
            "Handgun Mk II",
            ),
        'handgun_02_rare': Weapon(
            'handgun_02_rare',
            "Holepuncher",
            ),
        'handgun_03': Weapon(
            'handgun_03',
            "Handgun Mk III",
            ),
        'handgun_03_rare': Weapon(
            'handgun_03_rare',
            "Hexed Aura Gun",
            ),
        'handgun_04': Weapon(
            'handgun_04',
            "Handgun Mk IV",
            ),
        'handgun_04_rare': Weapon(
            'handgun_04_rare',
            "Tri-Shooter",
            ),
        'handgun_05': Weapon(
            'handgun_05',
            "Handgun Mk V",
            ),
        'handgun_05_rare': Weapon(
            'handgun_05_rare',
            "Piercing Handgun",
            ),
        'handgun_06': Weapon(
            'handgun_06',
            "Atomic Handgun",
            ),
        'handgun_captain': Weapon(
            'handgun_captain',
            "Leeway's Handgun",
            ),
        'rpg_00': Weapon(
            'rpg_00',
            "Antique Rocket Launcher",
            ),
        'rpg_01': Weapon(
            'rpg_01',
            "Rocket Launcher Mk I",
            ),
        'launcher_01_rare': Weapon(
            'launcher_01_rare',
            "Queen's Launcher",
            ),
        'rpg_02': Weapon(
            'rpg_02',
            "Rocket Launcher Mk II",
            ),
        'rpg_02_rare': Weapon(
            'rpg_02_rare',
            "Rampage",
            ),
        'rpg_03': Weapon(
            'rpg_03',
            "Rocket Launcher Mk III",
            ),
        'launcher_03_rare': Weapon(
            'launcher_03_rare',
            "Big B.",
            ),
        'rpg_04': Weapon(
            'rpg_04',
            "Rocket Launcher Mk IV",
            ),
        'rpg_04_rare': Weapon(
            'rpg_04_rare',
            "The Laser Pointer",
            ),
        'rpg_05': Weapon(
            'rpg_05',
            "Rocket Launcher Mk V",
            ),
        'launcher_05_rare': Weapon(
            'launcher_05_rare',
            "Burning Grenade Launcher",
            ),
        'rpg_06': Weapon(
            'rpg_06',
            "Atomic Launcher",
            ),
        'hammer_00': Weapon(
            'hammer_00',
            "Old Hammer",
            ),
        'hammer_01': Weapon(
            'hammer_01',
            "Hammer Mk I",
            ),
        'hammer_01_rare': Weapon(
            'hammer_01_rare',
            "Point Break",
            ),
        'hammer_02': Weapon(
            'hammer_02',
            "Hammer Mk II",
            ),
        'hammer_02_rare': Weapon(
            'hammer_02_rare',
            "Sunderer",
            ),
        'hammer_03': Weapon(
            'hammer_03',
            "Hammer Mk III",
            ),
        'hammer_03_rare': Weapon(
            'hammer_03_rare',
            "Razor Gear",
            ),
        'hammer_04': Weapon(
            'hammer_04',
            "Hammer Mk IV",
            ),
        'hammer_04_rare': Weapon(
            'hammer_04_rare',
            "Mjölner",
            ),
        'hammer_05': Weapon(
            'hammer_05',
            "Hammer Mk V",
            ),
        'hammer_05_rare': Weapon(
            'hammer_05_rare',
            "The Spartan",
            ),
        'hammer_06': Weapon(
            'hammer_06',
            "Atomic Hammer",
            ),
        'shotgun_00': Weapon(
            'shotgun_00',
            "Junkyard Shotgun",
            ),
        'shotgun_01': Weapon(
            'shotgun_01',
            "Shotgun Mk I",
            ),
        'shotgun_01_rare': Weapon(
            'shotgun_01_rare',
            "Double Shotgun",
            ),
        'shotgun_02': Weapon(
            'shotgun_02',
            "Shotgun Mk II",
            ),
        'shotgun_02_rare': Weapon(
            'shotgun_02_rare',
            "Prototype Shotgun",
            ),
        'shotgun_03': Weapon(
            'shotgun_03',
            "Shotgun Mk III",
            ),
        'shotgun_03_rare': Weapon(
            'shotgun_03_rare',
            "Discharger",
            ),
        'shotgun_04': Weapon(
            'shotgun_04',
            "Shotgun Mk IV",
            ),
        'shotgun_04_rare': Weapon(
            'shotgun_04_rare',
            "Slugshot Tumbler",
            ),
        'shotgun_05': Weapon(
            'shotgun_05',
            "Shotgun Mk V",
            ),
        'shotgun_05_rare': Weapon(
            'shotgun_05_rare',
            "Squarer",
            ),
        'shotgun_06': Weapon(
            'shotgun_06',
            "Atomic Shotgun",
            ),
        'katana_rare': Weapon(
            'katana_rare',
            "Katana",
            ),
        }

