#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

# Copyright (C) 2024 Christopher J. Kucera
#
# swh2save is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

import os
import sys
import zipfile
import datetime
import textwrap

import xml.etree.ElementTree as ET

def main():

    # TODO: I'd eventually like to make this more general, autodetect install
    # locations, and at least attempt to make it cross-platform.

    game_dir = '/games/Steam/steamapps/common/SteamWorld Heist 2'
    
    core_dir = os.path.join(game_dir, 'Bundle', 'Core')

    output_file = os.path.join('swh2save', 'gamedata.py')

    with open(output_file, 'w') as odf:

        print('# File has been autogenerated by gen_game_data.py', file=odf)
        print('# Generated on: {}'.format(
            datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat()
            ), file=odf)
        print("# Don't edit by hand!", file=odf)
        
        print(textwrap.dedent("""
            # Copyright (C) 2024 Christopher J. Kucera
            #
            # swh2save is free software: you can redistribute it and/or modify
            # it under the terms of the GNU General Public License as published by
            # the Free Software Foundation, either version 3 of the License, or
            # (at your option) any later version.
            #
            # This program is distributed in the hope that it will be useful,
            # but WITHOUT ANY WARRANTY; without even the implied warranty of
            # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
            # GNU General Public License for more details.
            #
            # You should have received a copy of the GNU General Public License
            # along with this program.  If not, see <http://www.gnu.org/licenses/>
            """), file=odf)
        print('', file=odf)

        with zipfile.ZipFile(os.path.join(core_dir, 'Game.pak')) as game_pak:

            # First up: a list of ship upgrades
            # TODO: get English labels for these as well
            with game_pak.open('Definitions/ship_upgrades.xml') as ship_upgrades:

                print('SHIP_UPGRADES = {', file=odf)
                root = ET.fromstring(ship_upgrades.read())
                for child in root:
                    if 'Abstract' in child.attrib:
                        continue
                    print("        '{}',".format(child.attrib['Name']), file=odf)
                print('        }', file=odf)
                print('', file=odf)

            # Now hats!
            # TODO: English labels, etc, etc.
            with game_pak.open('Definitions/hats.xml') as hat_xml:

                print('HATS = {', file=odf)
                root = ET.fromstring(hat_xml.read())
                for child in root:
                    if 'Abstract' in child.attrib:
                        continue
                    print("        '{}',".format(child.attrib['Name']), file=odf)
                print('        }', file=odf)
                print('', file=odf)

    print(f'Wrote to: {output_file}')


if __name__ == '__main__':
    main()

